spring:
  mail:
    host: localhost
    port: 25
    default-encoding: utf-8
    # for adding more properties see https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html
    properties:
      mail:
        mime:
          charset: utf-8
        smtp:
          allow8bitmime: true
          auth: fale
          from: my@niro.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
